# Generated by Django 4.2.27 on 2026-02-09 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('VALORANT', '발로란트'), ('OVERWATCH', '오버워치'), ('LOL', '리그오브레전드'), ('CS2', '카운터스트라이크2'), ('PUBG', '배틀그라운드'), ('APEX', '에이펙스 레전드'), ('R6', '레인보우식스 시즈'), ('FORTNITE', '포트나이트'), ('DOTA2', '도타2'), ('STARCRAFT', '스타크래프트'), ('MINECRAFT', '마인크래프트'), ('ETC', '기타')], max_length=20)),
                ('mode', models.CharField(choices=[('RANK', '랭크'), ('NORMAL', '일반'), ('CUSTOM', '내전'), ('ETC', '기타')], default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_members', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('OPEN', '모집중'), ('FULL', '마감'), ('CLOSED', '종료')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='parties.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='partymember',
            constraint=models.UniqueConstraint(fields=('party', 'user'), name='unique_party_member'),
        ),
    ]
