# Generated by Django 4.2.27 on 2026-02-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='accounts.game'),
        ),
    ]
