# Generated by Django 4.2.27 on 2026-02-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_alter_party_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='party',
            name='current_member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
