# Generated by Django 4.2.27 on 2026-02-11 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_alter_party_options_party_current_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='max_members',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)], verbose_name='최대 인원'),
        ),
        migrations.AlterField(
            model_name='party',
            name='mode',
            field=models.CharField(choices=[('RANK', '랭크'), ('NORMAL', '일반(비랭크)'), ('CUSTOM', '내전'), ('ETC', '기타')], default='NORMAL', max_length=20),
        ),
    ]
