# Generated by Django 4.2.27 on 2026-02-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_party_max_members_alter_party_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
