# Generated by Django 4.2.27 on 2026-02-14 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0010_blacklist_blacklist_unique_party_blacklist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blacklist',
            name='unique_party_blacklist',
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='parties.party'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_in_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(fields=('party', 'user'), name='unique_blacklist_entry'),
        ),
    ]
