# Generated by Django 4.2.27 on 2026-02-18 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0011_remove_blacklist_unique_party_blacklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='join_policy',
            field=models.CharField(choices=[('INSTANT', '즉시 입장'), ('APPROVAL', '승인제')], default='INSTANT', max_length=12, verbose_name='입장 방식'),
        ),
        migrations.CreateModel(
            name='PartyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '수락'), ('REJECTED', '거절'), ('CANCELLED', '취소')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_party_join_requests', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='parties.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='partyjoinrequest',
            constraint=models.UniqueConstraint(fields=('party', 'user'), name='unique_party_join_request'),
        ),
    ]
