# Generated by Django 4.2.27 on 2026-02-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0012_party_join_policy_partyjoinrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='parties.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='partywaitlist',
            constraint=models.UniqueConstraint(fields=('party', 'user'), name='unique_party_waitlist_entry'),
        ),
    ]
