# Generated by Django 4.2.27 on 2026-02-19 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_is_system_chatmessage_sender_name_and_more'),
        ('parties', '0013_partywaitlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_parties', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='party',
            name='pinned_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
