# Generated by Django 4.2.27 on 2026-02-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['party', 'created_at'], name='chat_chatme_party_i_af3529_idx'),
        ),
    ]
