# Generated by Django 4.2.27 on 2026-02-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.PositiveIntegerField(default=2000, help_text='출생년도 (예: 2002)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', '남'), ('FEMALE', '여'), ('OTHER', '기타'), ('PRIVATE', '비공개')], default='PRIVATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_games',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mic_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='temp_nickname', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='temp_phone', max_length=15, unique=True),
        ),
    ]
