# Generated by Django 4.2.27 on 2026-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_birth_year_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mic_enabled',
            field=models.CharField(choices=[('YES', '가능'), ('NO', '불가능')], max_length=3),
        ),
    ]
