# Generated by Django 4.2.27 on 2026-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_birth_year_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.PositiveIntegerField(default=999),
        ),
    ]
