# Generated by Django 4.2.27 on 2026-02-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_game_options_game_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mic_enabled',
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, help_text='출생년도 (예: 2002)', null=True),
        ),
    ]
