# Generated by Django 4.2.27 on 2026-02-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_mic_enabled_alter_user_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mic_enabled',
            field=models.BooleanField(default=False, help_text='마이크 사용 가능 여부'),
        ),
    ]
