# Generated by Django 4.2.27 on 2026-02-11 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_mic_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(blank=True, help_text='출생년도 (예: 2002)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
