# Generated by Django 4.2.27 on 2026-02-11 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=2000, help_text='출생년도 (예: 2002)', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
            preserve_default=False,
        ),
    ]
