# Generated by Django 4.2.27 on 2026-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(help_text='출생년도 (예: 2002)'),
        ),
    ]
